### ISSUE TITLE
Basic2D tests fail with `BadValue`

### ISSUE THREAD

**Issue by astrieanna** [rennis250/Processing.jl#3]
I ran `test/basic2D.jl`, but it has an error. Before the error, I see a small window rapidly pop-up (with some shapes and lines) and then disappear as the error happens.

~~~
$ julia test/basic2D.jl 
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (RENDER)
  Minor opcode of failed request:  5 (RenderChangePicture)
  Value in failed request:  0x5f
  Serial number of failed request:  122
  Current serial number in output stream:  170
~~~

I'm at the latest master of Processing.

**Comment by rennis250** [comment]
This package now uses OpenGL and GLFW. Cairo is there now only as a backup in the worst case scenario. Please let me know if things work better with the new contents.
