### ISSUE TITLE
GLUtil renamed to GLAbstraction

### ISSUE THREAD

**Issue by bvanevery** [rennis250/Processing.jl#4]
The package name is different now.  OpenGL test fails due to use of old name.

bvanevery@snazzy ~/.julia/v0.3/Processing/test $ julia basic2DOpenGL.jl
INFO: loaded GLFW 3.0.4 X11 GLX glXGetProcAddress clock_gettime /dev/js shared from /home/bvanevery/.julia/v0.3/GLFW/deps/usr64/lib/libglfw
ERROR: GLUtil not found
 in require at loading.jl:47
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in eval at no file
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_1713 at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
while loading /home/bvanevery/.julia/v0.3/Processing/src/Processing2DOpenGL.jl, in expression starting on line 5
while loading /home/bvanevery/.julia/v0.3/Processing/test/basic2DOpenGL.jl, in expression starting on line 14

**Comment by rennis250** [comment]
Done.
