### ISSUE TITLE
Error running basic2D.jl

### ISSUE THREAD

**Issue by tildebyte** [rennis250/Processing.jl#5]
This occurs in `basic2D.jl` at `coordSystem(-1, 1, 1, -1)` [1], which calls `Processing2D.jl` at `Base.Graphics.set_coords(cr, 0, 0, state.w, state.h, left, right, top, bottom)`

Which is bizarre, because the relevant `set_coords` signature is `set_coords(c::GraphicsContext, x, y, w, h, l, r, t, b)`, and I don't even see a type specification in there. Maybe I'm missing something implicit...

```
ERROR: `set_coords` has no method matching set_coords(::CairoContext, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64)
 in coordSystem at C:\Users\user\.julia\v0.3\Processing\src\Processing2D.jl:225
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at client.jl:285
 in _start at client.jl:354
while loading C:\Users\user\.julia\v0.3\Processing\test\basic2D.jl, in expression starting on line 5
```

[1] I feel your pain on this one. It's the one thing I truly *hate* about P5

**Comment by tildebyte** [comment]
Probably should have mentioned:
Win 7 Pro x64
Julia 0.3.6

**Comment by rennis250** [comment]
This package has undergone a complete re-design and the coordSystem() function will be reimplemented at a later date. Hopefully, it will not produce the same error in the future.
