### ISSUE TITLE
A couple of issues.

### ISSUE THREAD

**Issue by prcamp** [rennis250/Processing.jl#7]
I'm using a mac, and Pkg.test is failing with: 
```
ERROR: LoadError: MethodError: `./` has no method matching ./(::Tuple{UInt32,Float64,Float64}, ::Float32)
```
This is in shapes2d.jl at line 446. 

But it seems like the actual issue could be this warning:
```
WARNING: could not attach metadata for @simd loop.
```
When I call `rect(1,1,1,1)` from the REPL I get that warning, followed by
```
ERROR: BoundsError: attempt to access 0-element Array{UInt32,1}
  at index [0]
 in getindex at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in rect at /Users/prc/.julia/v0.4/Processing/src/shapes2d.jl:499
 in rect at /Users/prc/.julia/v0.4/Processing/src/shapes2d.jl:574
```

**Comment by rennis250** [comment]
The @simd error is common, if the loop doesn't match the signature that the macro expects, so that's nothing serious to worry about, but should be fixed eventually. I'll take a look into your problem. Just for testing though, could you try using the latest version of Julia (v0.4.5).

Thanks!

**Comment by rennis250** [comment]
Oh, nevermind, I know why you are getting that error. Are you using the latest version of Processing from this repo? I haven't had a chance to tag a number of fixes and improvements in the package manager yet. You will want to run ```Pkg.checkout("Processing")```.

**Comment by prcamp** [comment]
I'll give that a shot this weekend. Thanks.

**Comment by rennis250** [comment]
Sorry. I was stupidly testing something that was in development on my laptop. I pushed a quick fix that should resolve the problem for you.
